source 'https://rubygems.org'
ruby "2.2.4"

gem 'rake'
gem 'dashing'
gem 'ruby-trello'
gem 'pry'
gem 'octokit'
gem 'rest-client'
gem 'rspec'
gem 'ruby-gmail'
gem 'passenger'
gem 'redis-objects'
gem 'nokogiri'
gem 'plex-ruby'
gem 'mechanize'
gem 'pocket-ruby'
gem 'watir-webdriver'
