source 'https://rubygems.org'

gem 'rake'
gem 'dashing'
gem 'ruby-trello'
gem 'pry'
gem 'octokit'
gem 'rest-client', '1.8.0'
gem 'rspec'
gem 'ruby-gmail'
gem 'passenger'
gem 'redis-objects'
gem 'nokogiri'
gem 'plex-ruby'
gem 'mechanize'
gem 'pocket-ruby'
