source 'https://rubygems.org'

gem 'rake'
gem 'dashing'
gem 'ruby-trello', :git => 'git://github.com/camilleldn/ruby-trello.git'
gem 'pry'
gem 'octokit'
gem 'rest-client'
gem 'rspec'
gem 'ruby-gmail'
gem 'passenger'
gem 'redis-objects'
gem 'nokogiri'
gem 'plex-ruby'
gem 'mechanize'
gem 'pocket-ruby'
gem 'watir-webdriver'
